# theme = "monokai_pro_octagon"
theme = "zenburn"

[editor]
line-number = "relative"
true-color = true

[editor.lsp]
display-messages = true

[editor.indent-guides]
render = true
character = "⋮"

[keys.normal]
";" = "command_mode"
C-h = "goto_line_start"
C-l = "goto_line_end"
