# theme = "monokai_pro_octagon"
theme = "zenburn"

[editor]
line-number = "relative"
true-color = true
[editor.lsp]
display-messages = true

[keys.normal]
semicolon = "command_mode"
C-h = "goto_line_start"
C-l = "goto_line_end"